.\" Manpage for kraus.
.\" Contact toke@toke.de to correct errors or typos.
.TH man 1 "5 April 2015" "1.4.1" "kraus man page"
.SH NAME
kraus \- "Kaffee-Runde auf unterschiedlichen Stockwerken"
.SH SYNOPSIS
.B kraus [-h] [-w][-s
.I Strategy
.B] [-o
.I Output
.B ][-c
.I count
.B ]
.SH DESCRIPTION
kraus is a small application that prints out the "Floor of the day" on
which my coworkers are meeting for coffee.
.SH OPTIONS
.IP -o csv
Output "CSV"
.IP -o text
Output "plaintext"
.IP -o simple
Output "simple" just the floor
.IP -o json
Output "JSON"
.IP -o vcard
Output "vCARD"
.IP -o calendar
Output "calendar"
.IP -w
Supress output of weekends
.IP "-c count"
Output
.I count
concurrent days (obeys the -w flag)

.P If no arguments are given the floor of the current day is printed on stdout.
.SH SEE ALSO
kraus(1)

https://github.com/toke/craus/
.SH BUGS
No known bugs.
.SH AUTHOR
Thomas Kerpe (toke@toke.de)
